// controllers/AiController.js
const AiService = require('../services/AiService');
const AiPrompt = require('../models/AiPrompt');

class AiController {
  constructor(db) {
    this.aiService = new AiService();
    this.aiPromptModel = new AiPrompt(db);
  }

  async generateTemplate(req, res) {
    try {
      console.log('=== AI TEMPLATE GENERATION REQUEST ===');
      console.log('Request body received:', req.body);
      console.log('Request headers:', req.headers);
      console.log('Request method:', req.method);
      console.log('Request URL:', req.url);
      
      const { 
        description, 
        userId, 
        websiteType = 'general',
        style = 'modern',
        colorScheme = 'blue',
        includeSections = []
      } = req.body;

      console.log('Extracted parameters:', { description, userId, websiteType, style, colorScheme });

      if (!description) {
        console.log('ERROR: No description provided');
        return res.status(400).json({
          success: false,
          error: 'Website description is required'
        });
      }

      console.log('Generating template for:', { description, userId, websiteType, style, colorScheme });

      // Generate template using AI service
      const templateResult = await this.aiService.generateCompleteTemplate({
        description,
        websiteType,
        style,
        colorScheme,
        includeSections,
        userId: userId || 'anonymous'
      });

      if (!templateResult.success) {
        return res.status(500).json({
          success: false,
          error: templateResult.error || 'Failed to generate template'
        });
      }

      // Save the generated template to database
      const savedTemplate = await this.saveGeneratedTemplate({
        ...templateResult.template,
        userId: userId || 'anonymous',
        originalDescription: description
      });

      const response = {
        success: true,
        template: savedTemplate,
        reasoning: templateResult.reasoning,
        suggestions: templateResult.suggestions || []
      };
      
      console.log('Sending response:', response);
      res.json(response);

    } catch (error) {
      console.error('Generate Template Error:', error);
      res.status(500).json({
        success: false,
        error: 'Failed to generate template'
      });
    }
  }

  async saveGeneratedTemplate(templateData) {
    try {
      // Create a unique ID for the generated template
      const templateId = `generated_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;
      
      const template = {
        id: templateId,
        name: templateData.name || 'AI Generated Template',
        description: templateData.description || 'Generated by AI',
        category: templateData.category || 'ai-generated',
        image: templateData.image || '/api/placeholder/400/300',
        elements: templateData.elements || [],
        css_base: templateData.css_base || '',
        is_featured: false,
        tags: ['ai-generated', ...(templateData.tags || [])],
        created_at: new Date(),
        user_id: templateData.userId,
        original_description: templateData.originalDescription
      };

      // For now, return the template object
      // In a real implementation, you'd save this to the database
      return template;
    } catch (error) {
      console.error('Save Template Error:', error);
      throw error;
    }
  }
}

module.exports = AiController;


